<?php

$admin = filter_input(INPUT_GET, 'admin');
switch ($admin) {
    case 'home':include 'home.php';
        break;
    case 'produk': include 'daftar_produk.php';
        break;
    case 'cari_produk_by_nama':include 'produk_by_nama.php';
        break;
    case 'cetak_laporan_produk':include 'cetak_pdf_barang_go.php';
        break;
    case 'tambah_produk':include 'tambah_produk.php';
        break;
    case 'tambah_produk_finish':include 'tambah_produk_finish.php';
        break;
    case 'ubah_produk':include 'ubah_produk.php';
        break;
    case 'ubah_produk_finish':include 'ubah_produk_finish.php';
        break;
    case 'hapus_produk':include 'hapus_produk.php';
        break;
    case 'data_transaksi':include 'data_transaksi.php';
        break;
    case 'data_transaksi_detail':include 'data_transaksi_detail.php';
        break;
    case 'member_detail':include 'member_detail.php';
        break;
    case 'data_konfirmasi':include 'data_konfirmasi.php';
        break;
    case 'lihat_bukti_konfirmasi':include 'lihat_bukti_konfirmasi.php';
        break;
    case 'cetak_bukti_pembayaran':include 'cetak_bukti_pembayaran.php';
        break;
    case 'data_member':include 'data_member.php';
        break;
    case 'cari_member_by_nama':include 'member_by_nama.php';
        break;
    case 'cetak_laporan_per_periode': include 'cetak_pdf_transaksi_per_periode.php';
        break;
    case 'data_daerah':include 'data_daerah.php';
        break;
    case 'tambah_kabupaten':include 'tambah_kabupaten.php';
        break;
    case 'tambah_kabupaten_finish':include 'tambah_kabupaten_finish.php';
        break;
    case 'ubah_kabupaten':include 'ubah_kabupaten.php';
        break;
    case 'ubah_kabupaten_finish':include 'ubah_kabupaten_finish.php';
        break;
    case 'hapus_kabupaten':include 'hapus_kabupaten.php';
        break;
    case 'panduan_belanja':include_once 'panduan_belanja.php';
        break;
    case 'tambah_panduan':include 'tambah_panduan.php';
        break;
    case 'tambah_panduan_finish':include 'tambah_panduan_finish.php';
        break;
    case 'ubah_panduan':include 'ubah_panduan.php';
        break;
    case 'ubah_panduan_finish':include 'ubah_panduan_finish.php';
        break;
    case 'hapus_panduan':include 'hapus_panduan.php';
        break;
    case 'daftar_pabrikan':include 'daftar_pabrikan.php';
        break;
    case 'tambah_pabrikan':include 'tambah_pabrikan.php';
        break;
    case 'tambah_pabrikan_finish':include 'tambah_pabrikan_finish.php';
        break;
    case 'ubah_pabrikan':include 'ubah_pabrikan.php';
        break;
    case 'ubah_pabrikan_finish':include 'ubah_pabrikan_finish.php';
        break;
    case 'hapus_pabrikan':include 'hapus_pabrikan.php';
        break;
    case 'data_propinsi':include 'data_propinsi.php';
        break;
    case 'tambah_propinsi':include 'tambah_propinsi.php';
        break;
    case 'tambah_propinsi_finish':include 'tambah_propinsi_finish.php';
        break;
    case 'ubah_propinsi':include 'ubah_propinsi.php';
        break;
    case 'ubah_propinsi_finish':include 'ubah_propinsi_finish.php';
        break;
    case 'hapus_propinsi':include 'hapus_propinsi.php';
        break;
    case 'data_kabupaten':include 'data_kabupaten.php';
        break;
    case 'tambah_kecamatan':include 'tambah_kecamatan.php';
        break;
    case 'tambah_kecamatan_finish':include 'tambah_kecamatan_finish.php';
        break;
    case 'ubah_kecamatan':include 'ubah_kecamatan.php';
        break;
    case 'ubah_kecamatan_finish':include 'ubah_kecamatan_finish.php';
        break;
    case 'hapus_kecamatan':include 'hapus_kecamatan.php';
        break;
    case 'cari_kabupaten_by_nama':include 'kabupaten_by_nama.php';
        break;
    case 'cari_kecamatan_by_nama':include 'kecamatan_by_nama.php';
        break;
    case 'cari_propinsi_by_nama':include 'propinsi_by_nama.php';
        break;
    case 'cetak_member':include 'cetak_member.php';
        break;
    case 'ubah_admin':include 'ubah_admin.php';
        break;
    case 'ubah_admin_finish':include 'ubah_admin_finish.php';
        break;
    default :include 'home.php';
}
